### ISSUE TITLE
Remove config for publishers that don't need one

### ISSUE THREAD

**Issue by andrenarchy** [andrenarchy/libfulltext#12]
We should not have config entries like `springer: {}`.

**Comment by mfherbst** [comment]
You don't really need it. It is autogenerated if it is missing in the actual config file. I'll make that more clear in the README.md.

**Comment by andrenarchy** [comment]
Hm, my point is that we shouldn't have it in the config file. I'd love to keep the config small so it's really readable. Imagine we have all >9000 CrossRef members as publishers; only a couple of those actually need configuration (like API keys) but we'd have thousands of lines with empty dicts in our file.

**Comment by mfherbst** [comment]
Good point indeed. I have an idea how to achieve that. Essentially we generate an empty dict on the fly ... I'm on a PR.

**Comment by andrenarchy** [comment]
Fixed by #13.
