### ISSUE TITLE
Wie mit Angeboten für bulk download umgehen?

### ISSUE THREAD

**Issue by katrinleinweber** [andrenarchy/libfulltext#35]
Wie in #24 bemerkt, verweist PLoS zum Download des ganzen Archivs auf https://www.ncbi.nlm.nih.gov/pmc/tools/ftp/. Dort gibt es schon eingepackte XML- oder TXT-Versionen zum Massendownload, oder auch die PDFs direkt.

Ist sowas nützlich für uns?

**Comment by mfherbst** [comment]
It certainly is. We are not entirely sure how to deal with bulk downloads yet. One ansatz is discussed in #26.

(My reply is in English, since I suppose we should keep the discussion in English for later reference. Hope you don't mind ;-) )

**Comment by andrenarchy** [comment]
@katrinleinweber Definitely helpful! Let's gather all important information for bulk downloads in #26. Closing this one for now.
